export enum CONFIG {
  PORT = 'PORT',

  DB_URI = 'DB_URI',

  REFRESH_SECRET_KEY = 'REFRESH_SECRET_KEY',
  // REFRESH_EXPIRATION_TIME = 'REFRESH_EXPIRATION_TIME',

  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',

  RECOVERY_SECRET_KEY = 'RECOVERY_SECRET_KEY',
  RECOVERY_EXPIRATION_TIME = 'RECOVERY_EXPIRATION_TIME',

  BCRYPT_SALT_ROUNDS = 'BCRYPT_SALT_ROUNDS',

  GMAIL = 'GMAIL',
  GMAIL_PASSWORD = 'GMAIL_PASSWORD',
}
