export const CONFIG = {
  DB_URI: 'DB_URI',
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',
  REFRESH_SECRET_KEY: 'REFRESH_SECRET_KEY',
  BCRYPT_SALT_ROUNDS: 'BCRYPT_SALT_ROUNDS',
  CYPHER_ALGORITHM: 'CYPHER_ALGORITHM',
  PORT: 'PORT',
  GMAIL: 'GMAIL',
  GMAIL_PASSWORD: 'GMAIL_PASSWORD',
};
